title: Vikram Pawar
logo: /assets/img/vikram_pawar.png
description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/vikrampawar88/">LinkedIn</a> |
  <a href="https://vikrampawar88.github.io/portfolio/">GitHub</a>
  <br>   
  I'm working on Data Science, Big Data, Spark, Machine learning & NLP related problems.
  Also handing the Big Data from Ecommerce company.
  <br>
  </p>

theme: jekyll-theme-minimal
